apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-dep
  region: eu-north-1

nodeGroups:
  - name: worker-nodes
    instanceType: t3.micro
    desiredCapacity: 2
    ssh:
      publicKeyName: Stockholm-alex-key
