apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    env: prod
    app: main
    tier: frontend
    owner: AlexanderEfimov
spec:
  containers:
    - name: container-apache
      image: nginx:latest
      ports:
        - containerPort: 80

    - name: container-api
      image: tomcat:latest
      ports:
        - containerPort: 8080
